#!/bin/bash
# Copyright (C) 2018-2019 Mattias Ohlsson
# https://github.com/mattias-ohlsson/centos-libvirt-creator
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

set -e

self=$(basename "$0")

name="centos"
os_type="linux"
os_variant="centos7.0"
memory=1024
vcpus=2
disk_size=20

install_iso_path="/var/lib/libvirt/images/CentOS-7-x86_64-DVD-1810.iso"
storage_pool_path="/var/lib/libvirt/images"

TEMP=`getopt -o h -l help,name:,cpus:,memory:,disk:,iso:,locale:,language:,force -n $self -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$TEMP"

while true ; do
	case "$1" in
		-h|--help)
			echo "Usage: $self [OPTIONS]"
			echo ""
			echo "  --force          force install"
			echo "  --name NAME      name of the instance (default: $name)"
			echo "  --cpus CPUS      number of cpus (default: $vcpus)"
			echo "  --memory MEMORY  memory allocation in MiB (default: $memory)"
			echo "  --iso ISO        installation media path"
			echo "  -h, --help       display this help and exit"
			echo ""
			exit
			shift ;;
		--name) name=$2 ; shift 2 ;;
		--cpus) vcpus=$2 ; shift 2 ;;
		--memory) memory=$2 ; shift 2 ;;
		--disk) disk_size=$2 ; shift 2 ;;
		--iso) install_iso_path=$2 ; shift 2 ;;
		--force)
			force=true
			shift ;;
		--) shift ; break ;;
		*) echo "Internal error!" ; exit 1 ;;
	esac
done

command -v virsh >/dev/null || { echo "virsh: command not found"; \
 exit 1; }

command -v virt-install >/dev/null || { echo "virt-install: command not found"; \
 exit 1; }

command -v virt-sparsify >/dev/null || { echo "virt-sparsify: command not found"; \
 exit 1; }

if [[ "$name" =~ [^a-zA-Z0-9\-] ]]; then
	echo "$self: name: invalid literal for int() with base 10: $name"
	exit 1
fi

if [[ "$vcpus" =~ [^0-9] ]]; then
	echo "$self: cpus: invalid literal for int() with base 10: $vcpus"
	exit 1
fi

if [[ "$memory" =~ [^0-9] ]]; then
	echo "$self: memory: invalid literal for int() with base 10: $memory"
	exit 1
fi

if [[ "$disk_size" =~ [^0-9] ]]; then
	echo "$self: disk: invalid literal for int() with base 10: $disk_size"
	exit 1
fi

if virsh -q dominfo $name &> /dev/null; then
	if [ "$force" == "true" ]; then
		virsh -q destroy $name 2>/dev/null ||:
		virsh -q undefine $name 2>/dev/null ||:

		if [ -f "$storage_pool_path/$name.qcow2" ]; then
			rm "$storage_pool_path/$name.qcow2"
		fi
	else
	        echo "Guest name $name is already in use."
	        exit
	fi
fi

echo "$self: Installing instance: $name"
virt-install --name $name --os-type $os_type --os-variant $os_variant \
 --memory $memory --vcpus $vcpus \
 --disk path=$storage_pool_path/$name.qcow2,size=$disk_size \
 --location "$install_iso_path" \
 --initrd-inject "/usr/lib/$self/anaconda-ks.cfg" \
 --extra-args "ks=file:/anaconda-ks.cfg" \
 --check path_in_use=off --noautoconsole --wait -1 --noreboot

mv $storage_pool_path/$name.qcow2 $storage_pool_path/$name.qcow2-tmp
virt-sparsify --check-tmpdir ignore --compress $storage_pool_path/$name.qcow2-tmp $storage_pool_path/$name.qcow2
rm $storage_pool_path/$name.qcow2-tmp
